# FROM debian:9.5-slim
FROM ubuntu:latest

RUN echo "The release type is..."
RUN echo $RELEASE_TYPE

RUN echo "Body text"
RUN echo $BODY_TEXT

# ADD script.sh /script.sh
# RUN chmod +x /script.sh
# ENTRYPOINT ["/script.sh"]
