name: Alpha Release

on:
  issue_comment:
    types: [created, edited]

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '@alpha-deploy')
    steps:
    - uses: actions/checkout@v2
    - name: Docker Run
      uses: ./release-action
      env:
        RELEASE_TYPE: "alpha"
        BODY_TEXT: ${{ github.event.comment.body }}