name: Maiden Voyage

on:
  push:
    branchs: [ master ]
  pull_request:
    branchs: [ master ]

jobs:
  main_run:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Action
      uses: ./docker-action
      env:
        ACC_KEY: ${{ secrets.ACC_KEY }}
      # with:
      #   ACC_KEY: ${{ secrets.ACC_KEY }}

    # - shell: bash
    #   env:
    #     ACC_KEY: ${{ secrets.ACC_KEY }}
    #   run: |
    #     echo "${ACC_KEY}"