name: Nitro Upgrade

on:
  push:
    branchs: [ master ]
    # tags:
    #   - '*'
  pull_request:
    branchs: [ master ]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Action
      uses: ./nitro-upgrade-action
      env:
        ACC_KEY: ${{ secrets.ACC_KEY }}
      # with:
      #   ACC_KEY: ${{ secrets.ACC_KEY }}

    # - shell: bash
    #   env:
    #     ACC_KEY: ${{ secrets.ACC_KEY }}
    #   run: |
    #     echo "${ACC_KEY}"